/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MmKeyboard as MmKeyboard
} from './components/mm-keyboard/mm-keyboard';

declare global {
  interface HTMLMmKeyboardElement extends MmKeyboard, HTMLElement {
  }
  var HTMLMmKeyboardElement: {
    prototype: HTMLMmKeyboardElement;
    new (): HTMLMmKeyboardElement;
  };
  interface HTMLElementTagNameMap {
    "mm-keyboard": HTMLMmKeyboardElement;
  }
  interface ElementTagNameMap {
    "mm-keyboard": HTMLMmKeyboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mm-keyboard": JSXElements.MmKeyboardAttributes;
    }
  }
  namespace JSXElements {
    export interface MmKeyboardAttributes extends HTMLAttributes {
      disabled?: boolean;
      initialFreq?: number;
      initialVol?: number;
      maxFreq?: number;
      maxVol?: number;
      oscillatorType?: string;
    }
  }
}

