/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MmContext as MmContext
} from './components/mm-context/mm-context';

declare global {
  interface HTMLMmContextElement extends MmContext, HTMLElement {
  }
  var HTMLMmContextElement: {
    prototype: HTMLMmContextElement;
    new (): HTMLMmContextElement;
  };
  interface HTMLElementTagNameMap {
    "mm-context": HTMLMmContextElement;
  }
  interface ElementTagNameMap {
    "mm-context": HTMLMmContextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mm-context": JSXElements.MmContextAttributes;
    }
  }
  namespace JSXElements {
    export interface MmContextAttributes extends HTMLAttributes {
      alternativeContext?: AudioContext;
    }
  }
}


import {
  MmKey as MmKey
} from './components/mm-key/mm-key';

declare global {
  interface HTMLMmKeyElement extends MmKey, HTMLElement {
  }
  var HTMLMmKeyElement: {
    prototype: HTMLMmKeyElement;
    new (): HTMLMmKeyElement;
  };
  interface HTMLElementTagNameMap {
    "mm-key": HTMLMmKeyElement;
  }
  interface ElementTagNameMap {
    "mm-key": HTMLMmKeyElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mm-key": JSXElements.MmKeyAttributes;
    }
  }
  namespace JSXElements {
    export interface MmKeyAttributes extends HTMLAttributes {
      className?: string;
      frequency?: number;
      key?: string;
      time?: number;
      title?: string;
    }
  }
}


import {
  MmKeyboard as MmKeyboard
} from './components/mm-keyboard/mm-keyboard';

declare global {
  interface HTMLMmKeyboardElement extends MmKeyboard, HTMLElement {
  }
  var HTMLMmKeyboardElement: {
    prototype: HTMLMmKeyboardElement;
    new (): HTMLMmKeyboardElement;
  };
  interface HTMLElementTagNameMap {
    "mm-keyboard": HTMLMmKeyboardElement;
  }
  interface ElementTagNameMap {
    "mm-keyboard": HTMLMmKeyboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "mm-keyboard": JSXElements.MmKeyboardAttributes;
    }
  }
  namespace JSXElements {
    export interface MmKeyboardAttributes extends HTMLAttributes {
      disabled?: boolean;
      initialFreq?: number;
      initialVol?: number;
      maxFreq?: number;
      maxVol?: number;
      oscillatorType?: string;
    }
  }
}

